# Generated by Django 4.2.7 on 2023-12-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
    ]
